// AUTO-GENERATED by scripts/gen-limits (DEMO for the Smart Diff manual check).
// Do not edit by hand. Delete together with the demo commit.

export const DEFAULT_LIMITS: Readonly<Record<string, number>> = {
  '*': 60,
  '/api/public/users': 30,
  '/api/public/webhooks': 10,
  '/api/public/search': 120,
  '/api/public/export': 5,
};
