import type { CSSProperties } from "react";

export const s = {
  panel: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "14px 16px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    textAlign: "left",
  } satisfies CSSProperties,
  chevron: {
    marginLeft: "auto",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chevronOpen: {
    marginLeft: "auto",
    color: "var(--text-muted)",
    transform: "rotate(180deg)",
  } satisfies CSSProperties,
  body: {
    borderTopWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
  } satisfies CSSProperties,
  message: {
    padding: "14px 16px",
  } satisfies CSSProperties,
  messageMuted: {
    padding: "14px 16px",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  messageError: {
    padding: "14px 16px",
    fontSize: 12,
    color: "var(--crit)",
  } satisfies CSSProperties,
  item: {
    display: "flex",
    gap: 12,
    padding: "14px 16px",
    borderTopWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
  } satisfies CSSProperties,
  itemFirst: {
    display: "flex",
    gap: 12,
    padding: "14px 16px",
  } satisfies CSSProperties,
  rail: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    paddingTop: 7,
  } satisfies CSSProperties,
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 99,
    background: "var(--text-muted)",
  } satisfies CSSProperties,
  line: {
    flex: 1,
    width: 1,
    background: "var(--border)",
  } satisfies CSSProperties,
  content: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    gap: 10,
    alignItems: "baseline",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  link: {
    color: "var(--accent-text)",
    textDecoration: "none",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 14,
  } satisfies CSSProperties,
  title: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  notes: {
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
