#!/usr/bin/env node
// render.mjs — turns deps.json (from collect.mjs) into the fixed-structure Markdown report.
// Every number and table comes from deps.json; the only free text the model adds later is
// inside the <!-- model: … --> markers (Summary actions, refined advice, tier changes).
//
//   node render.mjs [--in <deps.json>] [--out <report.md>] [--root <repo>]

import fs from 'node:fs';
import path from 'node:path';

const args = parseArgs(process.argv.slice(2));
const ROOT = path.resolve(args.root ?? process.cwd());
const IN = path.resolve(args.in ?? path.join(ROOT, '.devdigest/cache/deps.json'));
const data = JSON.parse(fs.readFileSync(IN, 'utf8'));
const date = data.generatedAt.slice(0, 10);
const OUT = path.resolve(args.out ?? path.join(ROOT, 'docs/reports/dependencies', `${date}.md`));

const MB = 1024 * 1024;
const TIERS = ['P0', 'P1', 'P2', 'Info'];
const TIER_MEANING = {
  P0: 'Fix now — security exposure or a broken/irreproducible install.',
  P1: 'Fix this iteration — works today by accident, or will break on the next install/upgrade.',
  P2: 'Backlog — hygiene with a measurable payoff (MB, install time, clarity).',
  Info: 'Fact worth knowing — no action required unless it matters to you.',
};
const pkgByName = Object.fromEntries(data.packages.map((p) => [p.name, p]));


// ─── sections ───────────────────────────────────────────────────────────────────────────

function header() {
  return [
    `# Dependency report — ${date}`,
    '',
    `> Commit \`${data.commit ?? 'n/a'}\` on \`${data.branch ?? 'n/a'}\`${data.dirty ? ' (uncommitted changes present)' : ''} · mode **${data.mode}** · generated by the \`dependency-checker\` skill (\`collect.mjs\` → \`render.mjs\`). Numbers are facts from \`deps.json\`; regenerate rather than edit them.`,
  ].join('\n');
}

function scope() {
  const rows = data.packages.map((p) => [
    `\`${p.path}/\``, p.manager, p.lockfiles.join(', ') || '—', p.hasNodeModules ? 'yes' : '**no**',
    p.totals.direct.prod ?? 0, p.totals.direct.dev ?? 0, (p.totals.direct.peer ?? 0) + (p.totals.direct.optional ?? 0),
    p.usage.filesScanned,
  ]);
  return [
    '## Scope',
    '',
    `${data.packages.length} standalone packages (each with its own manifest and lock file; no workspace). Online checks (\`outdated\`, \`audit\`): **${data.mode === 'online' ? 'ran' : 'not run — pass `--online`'}**.`,
    '',
    table(['Package', 'Manager', 'Lock file', 'Installed', 'Prod', 'Dev', 'Peer/opt', 'Files scanned'], rows),
    '',
    '**How to read the numbers**',
    '',
    '- *Size* is apparent bytes of the installed files (`node_modules`), not what ships to a browser.',
    '- *Closure* = the dependency plus everything it pulls in. *Exclusive* = what removing it alone would free (parts shared with other direct deps excluded). Peer dependencies are billed to the package that declares them.',
    '- *Unused* means no import, script binary, string reference, `@types` target or peer use was found — a **candidate** to verify, not a verdict.',
    '- Internal edges come from `tsconfig` `paths`, relative imports that land in another package, same-named `src/vendor/*` copies, and declared runtime (HTTP) edges re-checked against their evidence file.',
  ].join('\n');
}

function graph() {
  return [
    '## Dependency graph',
    '',
    '### Components',
    '',
    componentGraph(),
    '',
    'Legend: solid arrow = compile-time alias (`tsconfig` `paths`) · thick arrow = relative import across packages · dotted arrow = runtime call (HTTP/browser) · dotted line = vendored copy (label shows drift). Red = an edge with a finding.',
    '',
    '### Heaviest and shared external dependencies',
    '',
    externalGraph(),
    '',
    'Per package: its 3 heaviest direct dependencies by closure, plus every dependency declared by several packages at **different** versions (red edges). Edge label = installed version.',
  ].join('\n');
}

function componentGraph() {
  const lines = ['```mermaid', 'flowchart LR'];
  const flagged = new Set(data.findings.filter((f) => f.tier === 'P0' || f.tier === 'P1').flatMap((f) => String(f.package).split(', ')));
  for (const p of data.packages) {
    lines.push(`  ${id(p.name)}["<b>${p.name}</b><br/>${p.manager} · ${fmt(p.totals.installedBytes)}<br/>${p.totals.direct.prod ?? 0} prod · ${p.totals.direct.dev ?? 0} dev"]`);
  }
  const red = [];
  data.edges.forEach((e) => {
    let line;
    if (e.kind === 'alias') line = `  ${id(e.from)} -->|"${e.label}"| ${id(e.to)}`;
    else if (e.kind === 'relative-import') { line = `  ${id(e.from)} ==>|"relative import${e.testOnly ? ' (tests)' : ''} ×${e.sites}"| ${id(e.to)}`; red.push(true); }
    else if (e.kind === 'vendored-copy') { line = `  ${id(e.from)} -.-|"${e.label}${e.drift ? ` · ${e.drift} file(s) differ` : ' · in sync'}"| ${id(e.to)}`; red.push(Boolean(e.drift)); }
    else if (e.kind === 'runtime') line = `  ${id(e.from)} -.->|"${e.label}${e.verified ? '' : ' (unverified)'}"| ${id(e.to)}`;
    if (e.kind === 'alias' || e.kind === 'runtime') red.push(false);
    lines.push(line);
  });
  red.forEach((r, i) => { if (r) lines.push(`  linkStyle ${i} stroke:#d33,stroke-width:2px`); });
  lines.push('  classDef flagged stroke:#d33,stroke-width:2px');
  const f = data.packages.filter((p) => flagged.has(p.name)).map((p) => id(p.name));
  if (f.length) lines.push(`  class ${f.join(',')} flagged`);
  lines.push('```');
  return lines.join('\n');
}

function externalGraph() {
  const lines = ['```mermaid', 'flowchart LR'];
  const deps = new Map(); // dep name → category
  const edges = [];
  const drifting = new Set(data.drift.filter((d) => d.level === 'major' || d.level === 'minor').map((d) => d.dep));
  for (const p of data.packages) {
    lines.push(`  ${id(p.name)}(["${p.name}"])`);
    const installed = p.declared.filter((d) => d.installed);
    const heavy = [...installed].sort((a, b) => b.closureBytes - a.closureBytes).slice(0, 3);
    const picked = new Set([...heavy, ...installed.filter((d) => drifting.has(d.name))]);
    for (const d of picked) {
      deps.set(d.name, { category: d.category, bytes: Math.max(deps.get(d.name)?.bytes ?? 0, d.closureBytes) });
      edges.push({ from: p.name, to: d.name, label: `${d.version}${d.kind === 'dev' ? ' dev' : ''}`, red: drifting.has(d.name) });
    }
  }
  for (const [name, v] of deps) lines.push(`  ${id('d_' + name)}["${name}<br/><i>${v.category}</i> · ${fmt(v.bytes)}"]:::${v.category.replace(/[^a-z]/g, '')}`);
  edges.forEach((e) => lines.push(`  ${id(e.from)} -->|"${e.label}"| ${id('d_' + e.to)}`));
  edges.forEach((e, i) => { if (e.red) lines.push(`  linkStyle ${i} stroke:#d33,stroke-width:2px`); });
  const palette = { framework: '#dbeafe', aillm: '#ede9fe', database: '#dcfce7', testing: '#fef9c3', buildtooling: '#f1f5f9', types: '#f1f5f9', ui: '#fce7f3', validation: '#ffedd5', vcscodeanalysis: '#e0f2fe', other: '#f5f5f4' };
  for (const [k, c] of Object.entries(palette)) lines.push(`  classDef ${k} fill:${c},stroke:#888,color:#111`);
  lines.push('```');
  return lines.join('\n');
}

function sizes() {
  const per = data.packages.map((p) => {
    const top = [...p.declared].filter((d) => d.installed).sort((a, b) => b.closureBytes - a.closureBytes)[0];
    return [`\`${p.name}\``, Object.values(p.totals.direct).reduce((a, b) => a + b, 0), p.totals.uniqueInstalled, fmt(p.totals.installedBytes), fmt(p.totals.prodClosureBytes), top ? `${top.name} (${fmt(top.closureBytes)})` : '—'];
  });
  const totalBytes = data.packages.reduce((a, p) => a + p.totals.installedBytes, 0);

  const all = data.packages.flatMap((p) => p.declared.filter((d) => d.installed).map((d) => ({ ...d, pkg: p.name })));
  const heaviest = all.sort((a, b) => b.closureBytes - a.closureBytes).slice(0, 15).map((d, i) => [
    i + 1, `\`${d.name}\``, d.pkg, d.kind, d.category, d.version, fmt(d.ownBytes), fmt(d.closureBytes), fmt(d.exclusiveBytes), d.transitiveCount, d.usage.how,
  ]);

  const cats = {};
  for (const p of data.packages) for (const [c, b] of Object.entries(p.totals.byCategory)) cats[c] = (cats[c] ?? 0) + b;
  const catRows = Object.entries(cats).sort((a, b) => b[1] - a[1]);
  const catCounts = {};
  for (const p of data.packages) for (const d of p.declared) if (d.installed) catCounts[d.category] = (catCounts[d.category] ?? 0) + 1;

  const inventory = data.packages.map((p) => [
    '<details>',
    `<summary><b>${p.name}</b> — ${p.declared.length} direct dependencies, ${fmt(p.totals.installedBytes)}</summary>`,
    '',
    table(['Dependency', 'Kind', 'Range', 'Installed', 'Category', 'Closure', 'Exclusive', 'Transitive', 'Used via', 'Evidence'],
      [...p.declared].sort((a, b) => (b.closureBytes ?? 0) - (a.closureBytes ?? 0)).map((d) => [
        `\`${d.name}\``, d.kind, `\`${d.range}\``, d.version ?? '**missing**', d.category ?? '—', d.installed ? fmt(d.closureBytes) : '—', d.installed ? fmt(d.exclusiveBytes) : '—', d.transitiveCount ?? '—', d.usage.how, d.usage.evidence.slice(0, 2).map((e) => `\`${e}\``).join('<br/>') || '—',
      ])),
    '',
    '</details>',
  ].join('\n'));

  return [
    '## Size breakdown',
    '',
    `Total installed across all packages: **${fmt(totalBytes)}** (each package installs its own copy; nothing is shared between packages).`,
    '',
    '### Per package',
    '',
    table(['Package', 'Direct deps', 'Unique installed pkgs', 'Installed size', 'Prod closure', 'Heaviest direct dep'], per),
    '',
    '### Heaviest direct dependencies (top 15 by closure)',
    '',
    table(['#', 'Dependency', 'Package', 'Kind', 'Category', 'Version', 'Own', 'Closure', 'Exclusive', 'Transitive', 'Used via'], heaviest),
    '',
    '### By category',
    '',
    table(['Category', 'Direct deps', 'Installed size', 'Share'], catRows.map(([c, b]) => [c, catCounts[c] ?? 0, fmt(b), `${((b / totalBytes) * 100).toFixed(1)}%`])),
    '',
    '```mermaid',
    'pie showData title Installed size by category (MB)',
    ...catRows.map(([c, b]) => `  "${c}" : ${(b / MB).toFixed(1)}`),
    '```',
    '',
    '### Full inventory',
    '',
    ...inventory,
  ].join('\n');
}

function findings() {
  const byTier = Object.fromEntries(TIERS.map((t) => [t, data.findings.filter((f) => f.tier === t)]));
  const backlog = data.findings.filter((f) => f.tier !== 'Info').map((f) => [f.id, f.tier, `\`${f.rule}\``, where(f), EFFORT[f.rule] ?? 'M', oneLine(f)]);
  const out = [
    '## Findings & Priorities',
    '',
    table(['Tier', 'Meaning', 'Count'], TIERS.map((t) => [`**${t}**`, TIER_MEANING[t], byTier[t].length])),
    '',
    'A tier comes from the rule table in `collect.mjs`. A reviewer may move a finding **one** tier, and writes the reason under it as `Tier changed: P2 → P1 — <reason>`.',
    '',
    '### Backlog (P0 → P2, ordered by tier, then rule)',
    '',
    backlog.length ? table(['ID', 'Tier', 'Rule', 'Where', 'Effort', 'Action'], backlog) : '_Nothing to fix._',
  ];
  for (const t of TIERS) {
    out.push('', `### ${t} — ${TIER_MEANING[t].split(' — ')[0]}`, '');
    if (!byTier[t].length) { out.push('None.'); continue; }
    for (const f of byTier[t]) out.push(findingBlock(f));
  }
  return out.join('\n');
}

function findingBlock(f) {
  const a = advice(f);
  return [
    `#### ${f.id} · \`${f.rule}\` · ${where(f)}`,
    '',
    `- **What:** ${f.summary}`,
    `- **Evidence:** ${f.evidence.map((e) => `\`${e}\``).join('; ') || '—'}`,
    `- **Advice:** ${a.text}`,
    ...(a.cmd ? [`- **Command:** \`${a.cmd}\``] : []),
    `- **Effort:** ${EFFORT[f.rule] ?? 'M'}`,
    '',
  ].join('\n');
}

function summary() {
  const total = data.packages.reduce((a, p) => a + p.totals.installedBytes, 0);
  const direct = data.packages.reduce((a, p) => a + p.declared.length, 0);
  const tiers = TIERS.map((t) => `${t}: ${data.findings.filter((f) => f.tier === t).length}`).join(' · ');
  const biggest = [...data.packages].sort((a, b) => b.totals.installedBytes - a.totals.installedBytes)[0];
  const freeable = data.findings.filter((f) => f.rule.startsWith('unused-dependency')).reduce((a, f) => a + (f.facts.exclusiveBytes ?? 0), 0);
  const actions = data.findings.filter((f) => f.tier !== 'Info').slice(0, 5).map((f, i) => `${i + 1}. **[${f.tier}] ${f.id}** — ${oneLine(f)}`);
  return [
    '## Summary',
    '',
    '### Key numbers',
    '',
    `- ${data.packages.length} packages · ${direct} direct dependencies · **${fmt(total)}** installed; largest: \`${biggest.name}\` (${fmt(biggest.totals.installedBytes)}).`,
    `- Findings — ${tiers}.`,
    `- Removing every unused candidate would free ~${fmt(freeable)} (exclusive bytes).`,
    `- Internal edges: ${countKinds()}.`,
    '',
    '### Top actions',
    '',
    '<!-- model: replace this list with 3–5 actions, highest tier first; merge findings that share one fix; cite finding ids; keep every number as written above. -->',
    actions.length ? actions.join('\n') : '1. Nothing above Info — no action needed.',
  ].join('\n');
}

// ─── advice catalog ─────────────────────────────────────────────────────────────────────

const EFFORT = {
  'vulnerability-high': 'S–M', 'lockfile-conflict': 'S', 'lockfile-missing': 'S', 'undeclared-runtime-import': 'S',
  'undeclared-test-import': 'S', 'dev-dep-in-runtime-code': 'S', 'tooling-in-prod': 'S', 'unused-dependency': 'S',
  'unused-dependency-heavy': 'S', 'loose-range': 'S', 'contract-lib-drift': 'S', 'version-drift-minor': 'S',
  'version-drift-major': 'L', 'outdated-major': 'M–L', 'deprecated': 'M', 'duplicate-versions': 'M',
  'cross-package-relative-import': 'M', 'cross-package-relative-import-test': 'M', 'vendored-copy-drift': 'M',
  'vulnerability-moderate': 'S–M', 'vulnerability-low': 'S', 'heavy-dependency': '—', 'not-installed': 'S', 'unresolved-specifier': '—',
};

function advice(f) {
  const p = pkgByName[f.package];
  const m = p?.manager ?? 'npm';
  const c = (verb) => `cd ${p?.path ?? f.package} && ${cmd(m, verb, f.dependency)}`;
  const decl = p?.declared.find((d) => d.name === f.dependency);
  switch (f.rule) {
    case 'unused-dependency':
    case 'unused-dependency-heavy':
      return { text: `Confirm it is not loaded dynamically or by a tool config, then remove it and run the package's typecheck and tests.${f.facts.exclusiveBytes ? ` Frees ~${fmt(f.facts.exclusiveBytes)}.` : ''}`, cmd: c('remove') };
    case 'tooling-in-prod':
      return { text: 'Move it to devDependencies: a production install should not ship build/test tooling.', cmd: `${c('remove')} && ${cmd(m, 'add-dev', `${f.dependency}@${decl?.range ?? 'latest'}`)}` };
    case 'dev-dep-in-runtime-code':
      return { text: 'Runtime code imports it, but `--prod` installs omit devDependencies. Move it to dependencies, or keep the import behind a dev-only path.', cmd: `${c('remove')} && ${cmd(m, 'add', `${f.dependency}@${decl?.range ?? 'latest'}`)}` };
    case 'undeclared-runtime-import':
      return { text: 'Declare it explicitly. Today it resolves only because another package hoists a copy; the next lock-file change can remove it.', cmd: c('add') };
    case 'undeclared-test-import':
      return { text: 'Declare it as a devDependency so the test does not depend on a hoisted transitive copy.', cmd: c('add-dev') };
    case 'loose-range':
      return { text: `Pin to a caret range of the installed version (\`^${decl?.version ?? 'x.y.z'}\`) so a fresh install cannot jump majors.` };
    case 'lockfile-conflict':
      return { text: `Keep only the lock file of the package's manager (\`${m}\`), delete the other, reinstall. Two lock files drift silently.` };
    case 'lockfile-missing':
      return { text: 'Run an install to generate the lock file and commit it.', cmd: `cd ${p?.path} && ${m} install` };
    case 'not-installed':
      return { text: 'Install before trusting this report — sizes and usage for this package are incomplete.', cmd: `cd ${p?.path ?? f.package} && ${m} install` };
    case 'version-drift-major':
    case 'contract-lib-drift':
    case 'version-drift-minor': {
      const pkgs = String(f.package).split(', ');
      const target = highest(f.evidence);
      const cmds = pkgs.map((n) => `cd ${pkgByName[n]?.path ?? n} && ${cmd(pkgByName[n]?.manager ?? 'npm', 'update', f.dependency)}`);
      const why = f.rule === 'version-drift-minor' ? 'Align on the next touch; low risk.' : f.facts.contract
        ? 'Types from the vendored shared contracts compile against each package\'s own copy, so a version split can type-check differently per package.'
        : 'Different majors mean different APIs across packages that share code.';
      return { text: `${why} Align every package on ${target ? `\`${target}\`` : 'one version'} (same range in each \`package.json\`), reinstall with each package's own manager.`, cmd: cmds.join(' ; ') };
    }
    case 'duplicate-versions':
      return { text: `Find who pulls the older copies and upgrade those parents (often a test or build tool). Dev-only duplicates cost disk and install time, not runtime.`, cmd: `cd ${p?.path} && ${m === 'pnpm' ? 'pnpm why' : 'npm ls'} ${f.dependency}` };
    case 'cross-package-relative-import':
    case 'cross-package-relative-import-test':
      return { text: `Reach the other package through a declared \`tsconfig\` alias or move the shared piece into the vendored shared contracts${f.rule.endsWith('test') ? ' (or a test-utils folder)' : ''}. A relative path couples the folder layouts and bypasses the package boundary.` };
    case 'vendored-copy-drift':
      return { text: 'The vendored copies differ. Diff them, decide which copy is upstream, and re-copy; then add a check (e.g. `diff -r` in CI) so they cannot drift again.' };
    case 'heavy-dependency':
      return { text: 'No action required. If it reaches a browser bundle, load it lazily (dynamic `import()`); if it is dev-only, the cost is install time only.' };
    case 'unresolved-specifier':
      return { text: 'No action. Listed so a reviewer can confirm these are strings or fixtures, not real imports.' };
    case 'vulnerability-high':
    case 'vulnerability-moderate':
    case 'vulnerability-low':
      return { text: 'Upgrade to a fixed version (direct or via its parent); re-run audit to confirm.', cmd: `cd ${p?.path} && ${m} audit${m === 'npm' ? ' fix' : ' --fix'}` };
    case 'outdated-major':
      return { text: 'Plan the upgrade: read the changelog for breaking changes, upgrade in its own PR, run the full test suite.', cmd: c('update-latest') };
    case 'deprecated':
      return { text: 'Deprecated upstream: find the replacement the maintainers recommend and migrate.' };
    default:
      return { text: 'See the rule in `collect.mjs`.' };
  }
}

function cmd(m, verb, dep) {
  const pn = { remove: 'pnpm remove', add: 'pnpm add', 'add-dev': 'pnpm add -D', update: 'pnpm update', 'update-latest': 'pnpm update --latest' };
  const np = { remove: 'npm uninstall', add: 'npm install', 'add-dev': 'npm install -D', update: 'npm update', 'update-latest': 'npm install' };
  const base = (m === 'pnpm' ? pn : np)[verb];
  return `${base} ${verb === 'update-latest' && m !== 'pnpm' ? `${dep}@latest` : dep}`;
}

function highest(evidence) {
  const vs = evidence.map((e) => /: (\d+\.\d+\.\d+)/.exec(e)?.[1]).filter(Boolean);
  return vs.sort((a, b) => cmpVer(b, a))[0];
}

function cmpVer(a, b) {
  const x = a.split('.').map(Number); const y = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return 0;
}

// ─── helpers ────────────────────────────────────────────────────────────────────────────

function where(f) { return [f.package, f.dependency].filter(Boolean).map((x) => `\`${x}\``).join(' · '); }
function oneLine(f) { return `${f.dependency ? `\`${f.dependency}\` — ` : ''}${f.summary}`.replace(/\|/g, '\\|'); }
function countKinds() {
  const c = {};
  for (const e of data.edges) c[e.kind] = (c[e.kind] ?? 0) + 1;
  return Object.entries(c).map(([k, v]) => `${v} ${k}`).join(', ') || 'none';
}
function table(head, rows) {
  const esc = (v) => String(v ?? '—').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  return [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(esc).join(' | ')} |`)].join('\n');
}
// Prefixed so a package named like a Mermaid keyword (`end`, `class`, `graph`) cannot break the diagram.
function id(s) { return `n_${s.replace(/[^A-Za-z0-9_]/g, '_')}`; }
function fmt(b) { return b == null ? '—' : b >= MB ? `${(b / MB).toFixed(1)} MB` : `${Math.round(b / 1024)} KB`; }
function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) if (argv[i].startsWith('--')) out[argv[i].slice(2)] = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
  return out;
}

function main() {
  // A report whose model marker is gone already holds verification notes and Top actions;
  // re-rendering over it would silently drop them.
  if (fs.existsSync(OUT) && !args.force && !fs.readFileSync(OUT, 'utf8').includes('<!-- model:')) {
    console.error(`refusing to overwrite ${path.relative(ROOT, OUT)}: it already has model-written notes. Use --out <other.md> and diff, or --force.`);
    process.exit(2);
  }
  const md = [header(), scope(), graph(), sizes(), findings(), summary()].join('\n\n') + '\n';
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, md);
  console.log(`report → ${path.relative(ROOT, OUT)}`);
}

main();
