import type { CSSProperties } from "react";

export const s = {
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  } satisfies CSSProperties,
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  note: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--warn)",
  } satisfies CSSProperties,
  coverageBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "12px 14px",
  } satisfies CSSProperties,
  coverageTitle: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  coverageText: {
    margin: 0,
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  coverageList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  coverageRow: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  coverageLine: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  coverageRefs: {
    listStyle: "none",
    margin: "4px 0 0 4px",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  alert: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 13,
    color: "var(--crit)",
  } satisfies CSSProperties,
  link: {
    color: "var(--accent-text)",
    textDecoration: "underline",
  } satisfies CSSProperties,
  muted: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  status: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  costLines: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  costLine: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "flex-end",
    gap: 8,
    fontSize: 11.5,
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  costLabel: {
    color: "var(--text-muted)",
    marginRight: "auto",
  } satisfies CSSProperties,
  costFlow: {
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  summaryCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 18,
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  focusCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  focusHeading: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "0 0 12px",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  focusList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  focusItem: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
  } satisfies CSSProperties,
  focusBullet: {
    color: "var(--accent-text)",
    fontSize: 12,
    flexShrink: 0,
  } satisfies CSSProperties,
  riskCard: {
    display: "flex",
    alignItems: "stretch",
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-base, transparent)",
    width: "fit-content",
    maxWidth: "100%",
  } satisfies CSSProperties,
  riskMain: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: "6px 10px",
    minWidth: 0,
  } satisfies CSSProperties,
  chevron: {
    background: "none",
    border: "none",
    borderLeft: "1px solid var(--border)",
    padding: "0 10px",
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))",
    gap: 16,
    alignItems: "start",
  } satisfies CSSProperties,
  heading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13.5,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskTitle: {
    fontWeight: 600,
    flex: 1,
  } satisfies CSSProperties,
  riskBody: {
    margin: "6px 0 0 4px",
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  refs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    margin: "6px 0 0 4px",
  } satisfies CSSProperties,
  refButton: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--accent-text)",
    textAlign: "left",
  } satisfies CSSProperties,
} as const;
