import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    gap: 24,
    flexWrap: "wrap",
    marginBottom: 14,
  } satisfies CSSProperties,
  statValue: {
    fontSize: 20,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginRight: 6,
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  muted: {
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  node: {
    borderTop: "1px solid var(--border)",
    paddingTop: 8,
    marginTop: 8,
  } satisfies CSSProperties,
  nodeButton: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    textAlign: "left",
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    gap: 8,
    alignItems: "baseline",
    fontSize: 13,
    color: "var(--text-secondary)",
    padding: "3px 0 3px 18px",
  } satisfies CSSProperties,
  link: {
    color: "var(--accent)",
    textDecoration: "none",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
  } satisfies CSSProperties,
  subLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "8px 0 4px 18px",
  } satisfies CSSProperties,
  listItem: {
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
    padding: "2px 0 2px 18px",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 14,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  toggle: {
    display: "flex",
    gap: 6,
    marginBottom: 12,
  } satisfies CSSProperties,
  toggleButton: {
    fontSize: 12,
    padding: "3px 10px",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-secondary)",
    background: "transparent",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  toggleButtonActive: {
    color: "var(--text-primary)",
    background: "var(--bg-hover, var(--bg-elevated))",
    borderColor: "var(--accent)",
  } satisfies CSSProperties,
  graphWrap: {
    overflowX: "auto",
  } satisfies CSSProperties,
  errorLine: {
    fontSize: 12,
    color: "var(--crit)",
  } satisfies CSSProperties,
} as const;
