import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  headRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 14,
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    gap: 20,
    flexWrap: "wrap",
    alignItems: "center",
  } satisfies CSSProperties,
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  statValue: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  muted: {
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  node: {
    marginTop: 8,
  } satisfies CSSProperties,
  nodeButton: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "var(--bg-hover)",
    border: "none",
    borderRadius: 6,
    padding: "9px 12px",
    cursor: "pointer",
    fontSize: 14,
    color: "var(--text-primary)",
    textAlign: "left",
  } satisfies CSSProperties,
  symbolName: {
    fontFamily: "var(--font-mono, monospace)",
    fontWeight: 600,
  } satisfies CSSProperties,
  symbolIcon: {
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  callerCount: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  nodeBody: {
    marginTop: 8,
    marginLeft: 22,
  } satisfies CSSProperties,
  guide: {
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 1,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
    paddingLeft: 10,
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 13,
    color: "var(--text-muted)",
    padding: "5px 0",
  } satisfies CSSProperties,
  callerRowDeep: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 13,
    color: "var(--text-muted)",
    padding: "5px 0 5px 20px",
  } satisfies CSSProperties,
  link: {
    color: "var(--text-secondary)",
    textDecoration: "none",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
  } satisfies CSSProperties,
  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    margin: "8px 0 0 12px",
  } satisfies CSSProperties,
  chipEndpoint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    borderRadius: 6,
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  chipCron: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    borderRadius: 6,
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    background: "var(--warn-bg)",
    color: "var(--warn)",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 14,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  toggle: {
    display: "inline-flex",
    padding: 2,
    gap: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
  } satisfies CSSProperties,
  toggleButton: {
    fontSize: 13,
    padding: "4px 14px",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-muted)",
    background: "transparent",
    border: "none",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  toggleButtonActive: {
    fontSize: 13,
    padding: "4px 14px",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-primary)",
    background: "var(--bg-hover)",
    border: "none",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  divider: {
    height: 1,
    background: "var(--border)",
    margin: "18px 0",
  } satisfies CSSProperties,
  graphWrap: {
    overflowX: "auto",
  } satisfies CSSProperties,
  legend: {
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 12,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  legendItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  legendDot: (background: string) =>
    ({
      width: 8,
      height: 8,
      borderRadius: "50%",
      display: "inline-block",
      background,
    }) satisfies CSSProperties,
  errorLine: {
    fontSize: 12,
    color: "var(--crit)",
  } satisfies CSSProperties,
} as const;
