import type { CSSProperties } from "react";

/** Co-located styles for InlineFinding — a route-owned card matching the
    "webhooks.ts" mockup (spec 007, AC21/D19-B), distinct from FindingCard's
    own styles. Four-side longhand border widths/colors, `borderStyle` kept as
    one shorthand since it never differs per side (client/insights/gotchas.md). */
export const s = {
  card: (sevColor: string, muted: boolean): CSSProperties => ({
    position: "relative",
    margin: "6px 14px 8px 58px",
    borderRadius: 8,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: sevColor,
    background: "var(--bg-elevated)",
    opacity: muted ? 0.7 : 1,
  }),
  header: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "12px 34px 10px 12px",
  } satisfies CSSProperties,
  iconSquare: (bg: string, color: string): CSSProperties => ({
    flexShrink: 0,
    width: 24,
    height: 24,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: bg,
    color,
  }),
  headerMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  sevWord: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color,
  }),
  title: (muted: boolean): CSSProperties => ({
    fontSize: 13.5,
    fontWeight: 600,
    color: muted ? "var(--text-muted)" : "var(--text-primary)",
  }),
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  closeBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 22,
    height: 22,
    borderRadius: 5,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  } satisfies CSSProperties,
  body: { padding: "0 12px 14px" } satisfies CSSProperties,
  prose: { fontSize: 13.5, lineHeight: 1.6, color: "var(--text-secondary)" } satisfies CSSProperties,
  suggestionWrap: { marginTop: 12 } satisfies CSSProperties,
  suggestionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    marginBottom: 6,
    textTransform: "uppercase",
  } satisfies CSSProperties,
  actions: { display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" } satisfies CSSProperties,
  stub: (sevColor: string): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxSizing: "border-box",
    margin: "6px 14px 8px 58px",
    padding: "8px 12px",
    borderRadius: 8,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: sevColor,
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    font: "inherit",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    textAlign: "left",
  }),
  stubIcon: (color: string): CSSProperties => ({
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    color,
  }),
  stubTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
} as const;
