import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "24px 32px 10px" } satisfies CSSProperties,
  top: { display: "flex", alignItems: "flex-end", gap: 16 } satisfies CSSProperties,
  titleWrap: { minWidth: 0 } satisfies CSSProperties,
  title: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  meta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 14,
    color: "var(--text-secondary)",
    marginTop: 4,
  } satisfies CSSProperties,
  actions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  willUse: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  stale: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 12,
    padding: "8px 12px",
    fontSize: 13,
    color: "var(--warn)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  failure: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
    padding: "8px 12px",
    fontSize: 13,
    color: "var(--crit)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  failureMsg: { color: "var(--text-secondary)" } satisfies CSSProperties,
  link: { color: "var(--accent)" } satisfies CSSProperties,
} as const;
