import type { CSSProperties } from "react";

export const s = {
  summary: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.55,
    fontStyle: "italic",
  } satisfies CSSProperties,
  scopeColumns: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 20,
    marginTop: 14,
  } satisfies CSSProperties,
  scopeTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  scopeItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
    marginBottom: 6,
  } satisfies CSSProperties,
  meta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  sourcesTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginTop: 14,
    marginBottom: 8,
  } satisfies CSSProperties,
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 4,
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 6,
    padding: "8px 10px",
    marginTop: 14,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
  } satisfies CSSProperties,
  errorLine: {
    fontSize: 12.5,
    color: "var(--crit)",
  } satisfies CSSProperties,
  emptyHint: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginTop: 4,
  } satisfies CSSProperties,
} as const;
